### ISSUE TITLE
Odometrie orientation

### ISSUE THREAD

**Issue by lchop** [laboshinl/loam_velodyne#134]
Hello,

I have an issue with the odometrie orientation.
https://www.youtube.com/watch?v=YTCnmP5RBuE
The yellow arrow is not pointing in the direction where the robot is going but instead it is "horizontal". 
I have the same issue here in the following picture with red arrow representing the odom:
![Screenshot from 2019-04-18 11-38-16](https://user-images.githubusercontent.com/36415141/56669831-0e33d300-66b2-11e9-87e7-2688729550ab.png)
I have correct it applying a PI/2 rotation to the odom message:
![Screenshot from 2019-04-18 11-48-56](https://user-images.githubusercontent.com/36415141/56669882-23106680-66b2-11e9-9644-8b06ed26a4cf.png)

But I am not happy with this fixe. Anyone has experienced this issue ? Is this even an issue ?

**Comment by YoshuaNava** [comment]
This is due to LOAM using a camera coordinate frame convention. It's described in the author's papers.

If you want to have a quick fix, just rotate the output poses/clouds of LOAM to your desired coord. frame orientation.

For a more elaborate, long term fix you'd need to dive deeper into the code. It performs all the calculations in the camera coordinate frame, so there is quite that would need to be changed.

**Comment by lchop** [comment]
Hello,

Thank you for your answers. I have read the author's paper, two frames are mentionned, a world frame W and a Laser Frame L. Just to be sure, the camera frame convention is applied to the 3D laser Frame, is that correct ?

**Comment by YoshuaNava** [comment]
> Hello,
> 
> Thank you for your answers. I have read the author's paper, two frames are mentionned, a world frame W and a Laser Frame L. Just to be sure, the camera frame convention is applied to the 3D laser Frame, is that correct ?

And to the IMU.
