### ISSUE TITLE
Changing axis of map and odometry

### ISSUE THREAD

**Issue by ashnarayan13** [laboshinl/loam_velodyne#64]
Hi, 

The direction of motion for my vehicle is in the Z axis as per loam. I do not know why. I have enclosed two screen shots of the LOAM. It directly starts perpendicular to the grid in RVIZ. 

![screenshot from 2018-05-03 09-03-02](https://user-images.githubusercontent.com/6239730/39559025-d49f8216-4eb0-11e8-9a61-a384a02245f0.png)
![screenshot from 2018-05-03 09-03-05](https://user-images.githubusercontent.com/6239730/39559026-d4e17c20-4eb0-11e8-92c9-6dca154885d8.png)

You can see that the LOAM considers the vehicle to be moving in the Z axis. Is there any way to alter this? When I just play the data (PCAP file) with the velodyne driver, the direction of motion is in the X axis. 

Screenshot from Velodyne 
![screenshot from 2018-05-03 09-08-04](https://user-images.githubusercontent.com/6239730/39559126-8daa024a-4eb1-11e8-83f3-0af1f5d4e386.png)

I could rotate the final pointcloud, but I will also have to rotate the odometry in that case. I was wondering if this is an issue with my data or it is an issue with LOAM and if so, is there a way to fix it in the code.

I would like to rotate the axis to the general ROS convention. (X forward, Z upwards). This is required for path planning. I wanted to know which part of the code I should work with to change the orientation as even the input pointcloud is rotated in LOAM. 

Thanks!

**Comment by Zhehua-Hu** [comment]
You can change Rviz Grid setting to 'XZ'.

**Comment by RozDavid** [comment]
I would have the exact same question as @ashnarayan13!

**Comment by ashnarayan13** [comment]
@RozDavid , I just had a static transform to handle this. But this doesn't solve the issue of the odometry being in a different frame. 
@Zhehua-Hu , I want to change the odometry in the LOAM output

**Comment by w4rlock999** [comment]
@ashnarayan13 have you resolved this problem? i'd like to know as i got this problem too

**Comment by RozDavid** [comment]
Hi @ashnarayan13 @w4rlock999 , I succeeded to resolve the convention issue, for changing the odometry frame a few months ago, just forgot to share it with you guys... Really sorry for that. So after including a static broadcaster in the launch file, something like this:
`<node pkg="tf2_ros" type="static_transform_publisher" name="loam_broadcaster" args="0 0 0 0.5 0.5 0.5 0.5 world imu_new"/>`

You still need the change the frames rotation quaternion with simply changing the axises. Either the imu or aft_mapped, both works similarly, it depends only on your purpose. 

You can check my solution here: 
https://github.com/RozDavid/loam-segmatch/blob/d1af9f5116e8c6fc5040d6f2f06868e905dcd7f2/src/lib/LaserOdometry.cpp#L908

In this case I included an extra frame for the static transform, then an extra static at the end, but neither of them are essential, only was important for me.

**Comment by w4rlock999** [comment]
@RozDavid so, what is the purpose of the static broadcaster you make in the launch file? I dont understand? 
And also my laserodometry.cpp already use the orientation you use like this:
` laserOdometryTrans.setRotation(tf::Quaternion(-geoQuat.y, -geoQuat.z, geoQuat.x, geoQuat.w));`
but it is still moving in the Z directions in the Rviz, the Odometry data (/laser_odom_to_init) also move in Z axis.
could you help me?

**Comment by nickcharron** [comment]
I'm also having this same problem. Has anyone found a solution?

I hacked together a solution by making a new node that subscribes to the odometry, switches the axes around (for position and orientation) and then re-publishes. But I would like to fix it in the loam code.

It seems like they switch the axes around before processing each scan: 
 https://github.com/laboshinl/loam_velodyne/blob/ef1b9b7287438de9284c68ab39a172cff1eff1ff/src/lib/MultiScanRegistration.cpp#L182 

I tried to change those three lines and that caused more issues. It must be hard coded somewhere else too. Any help would be appreciated.

**Comment by nickcharron** [comment]
LOAM switches the axes for each scan before processing the scan. I assume the reason this is done has something to do with the standard coordinate frame from of the velodyne which I believe is z-forward. The x-forward convention is a ROS convention and I believe the ROS driver converts to the scans to the proper ROS convention. I imagine LOAM was written for the velodyne convention, not the ROS convention.

To fix this, change the lines 182-184 to:
    point.x = laserCloudIn[i].x;
    point.y = laserCloudIn[i].y;
    point.z = laserCloudIn[i].z;
link: https://github.com/laboshinl/loam_velodyne/blob/ef1b9b7287438de9284c68ab39a172cff1eff1ff/src/lib/MultiScanRegistration.cpp#L182

Then, since they make an assumption on which axes correspond to the horizontal and vertical axes, you also need to change the following lines:

https://github.com/laboshinl/loam_velodyne/blob/ef1b9b7287438de9284c68ab39a172cff1eff1ff/src/lib/MultiScanRegistration.cpp#L199

to:

float angle = std::atan(point.z / std::sqrt(point.y * point.y + point.x * point.x));

and

https://github.com/laboshinl/loam_velodyne/blob/ef1b9b7287438de9284c68ab39a172cff1eff1ff/src/lib/MultiScanRegistration.cpp#L206

to

float ori = -std::atan2(point.y, point.x);

That should fix it! Hope this helps.

**Comment by ashnarayan13** [comment]
@nickcharron Thank you for the clarity.
